### PR TITLE
Bugfix__Correct input of min_y&min_x

### PR DESCRIPTION
**Pull request by ernOho**
Hi,
I apologize for opening and closing this pull request xD

It seems that there was a typo. This causes a error when trying to set different min_x and min_y(for eg. min_x = 5, min_y=0).
I am not entirely sure if this fixes the problem, but I think its a step into the right direction.

If I am mistaken I apologize in advance!

Kind regards,
E

### CODE REVIEW

**Comment by smueller18** [comment]
Hi @ernOho,

again I slightly remember that the original code is correct, because the plot and the array are transposed to each other. Here is a post on stackoverflow which I think describes this behavior: https://stackoverflow.com/a/44062487

But I will check this again at the weekend and will generate some plots to verify.

**Comment by ernOho** [comment]
Hi @smueller18 

Thank you so much for such a fast response. I appreciate it a lot that you will take a look at it again. I've attached pictures with different parameters and their indiviudal error messages/not expected results. 

The first error goes away when I apply what I did in this pull request.(not sure if it the correct way)
The source of the second error is in line 53 - 58, and should be cleared when are rounded correctly(This seems to be a well known, but confusing problem.). It seems that a trusted amount numbers should be allowed to be taken into consideration when rounding. But I actually am not to sure yet how to handle these problems.
And the bug, that the wrong axis change inputs should be cleared when swapping cell_grid_y and cell_grid_x in line 61.

But I am not certain about any of these suggestions and I would appreciate it a lot if you can confirm or find the solution to these errors/set a limit to what parameters may be inputed :)

Again, if I am mistaken I apologize for wasting your time!

regards
error_example1
error_example1_message
error_example2
error_example2_message
wrong_axis_example

**Comment by cl90** [comment]
This is connected to https://github.com/smueller18/TDKernelDMVW/issues/6, but I'm afraid it does not provide a complete solution.

**Comment by cl90** [comment]
Superseded by https://github.com/smueller18/TDKernelDMVW/pull/7

**Comment by smueller18** [comment]
fixed by #7

**Pull request closed without merging**
